shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/**'
  - 'packages/*'
  - 'configs/*'
  - 'examples/*'
  - e2e

overrides:
  # Required by Nativewind
  # - https://www.nativewind.dev/v5/getting-started/installation#5-override-the-lightningcss-version
  lightningcss: 1.30.1
